<?php return array(
    'root' => array(
        'name' => 'mediawiki/core',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => '70e5827aa7489664b8256b798b70bed5954fcd54',
        'type' => 'mediawiki-core',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => false,
    ),
    'versions' => array(
        'composer/installers' => array(
            'pretty_version' => 'v2.3.0',
            'version' => '2.3.0.0',
            'reference' => '12fb2dfe5e16183de69e784a7b84046c43d97e8e',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/./installers',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/semver' => array(
            'pretty_version' => '3.3.2',
            'version' => '3.3.2.0',
            'reference' => '3953f23262f2bff1919fc82183ad9acb13ff62c9',
            'type' => 'library',
            'install_path' => __DIR__ . '/./semver',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'cssjanus/cssjanus' => array(
            'pretty_version' => 'v2.1.1',
            'version' => '2.1.1.0',
            'reference' => 'befd1eb7b1e70ee2cd71cd5b9a86ff250d2e8423',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cssjanus/cssjanus',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'data-values/common' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '9f5e6216ec66ac8f2281351b110bad0eded43e65',
            'type' => 'library',
            'install_path' => __DIR__ . '/../data-values/common',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'data-values/data-values' => array(
            'pretty_version' => '3.1.0',
            'version' => '3.1.0.0',
            'reference' => '1084142918095dfedf9b6cc0de0755f8c4628264',
            'type' => 'library',
            'install_path' => __DIR__ . '/../data-values/data-values',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'data-values/geo' => array(
            'pretty_version' => '4.4.0',
            'version' => '4.4.0.0',
            'reference' => '1dd742dabb63e211862486259b2cbe0274211bf9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../data-values/geo',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'data-values/interfaces' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => '244d078954bc05edf8f8c6b088e848289171c3a8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../data-values/interfaces',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'data-values/validators' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => '83dbac2c5e9442e8fa2119c8b941ecb88156abe8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../data-values/validators',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '7.4.5',
            'version' => '7.4.5.0',
            'reference' => '1dd98b0564cb3f6bd16ce683cb755f94c10fbd82',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => '1.5.3',
            'version' => '1.5.3.0',
            'reference' => '67ab6e18aaa14d753cc148911d273f6e6cb6721e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '2.4.5',
            'version' => '2.4.5.0',
            'reference' => '0454e12ef0cd597ccd2adb036f7bda4e7fface66',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'jeroen/file-fetcher' => array(
            'pretty_version' => '6.1.0',
            'version' => '6.1.0.0',
            'reference' => 'd38fb0587b52b28bd24fda599f2da69ac8530453',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jeroen/file-fetcher',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'justinrainbow/json-schema' => array(
            'pretty_version' => '5.2.11',
            'version' => '5.2.11.0',
            'reference' => '2ab6744b7296ded80f8cc4f9509abbff393399aa',
            'type' => 'library',
            'install_path' => __DIR__ . '/../justinrainbow/json-schema',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'liuggio/statsd-php-client' => array(
            'pretty_version' => 'v1.0.18',
            'version' => '1.0.18.0',
            'reference' => 'c42e6d6687b7b2d7683186ec7f4f03351cc3dbca',
            'type' => 'library',
            'install_path' => __DIR__ . '/../liuggio/statsd-php-client',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mediawiki/core' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '70e5827aa7489664b8256b798b70bed5954fcd54',
            'type' => 'mediawiki-core',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mediawiki/data-values' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'mediawiki/http-request' => array(
            'pretty_version' => '1.3.1',
            'version' => '1.3.1.0',
            'reference' => 'a7cf33bae82cffe570086fc06d6617e802c0cc74',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mediawiki/http-request',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mediawiki/mediawiki' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.39.10',
            ),
        ),
        'mediawiki/parser-hooks' => array(
            'pretty_version' => '1.6.1',
            'version' => '1.6.1.0',
            'reference' => '45660efef737bcf33abbbb12c1ddb049c4e713fe',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mediawiki/parser-hooks',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mediawiki/semantic-media-wiki' => array(
            'pretty_version' => '4.1.3',
            'version' => '4.1.3.0',
            'reference' => 'b5e2afe11991fe21a335cb90426de24b85bc9fe7',
            'type' => 'mediawiki-extension',
            'install_path' => __DIR__ . '/../../extensions/SemanticMediaWiki',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mediawiki/semantic-result-formats' => array(
            'pretty_version' => '4.2.0',
            'version' => '4.2.0.0',
            'reference' => 'c07e5be3f26750c8821b0153c57e0ced9c5f6ed3',
            'type' => 'mediawiki-extension',
            'install_path' => __DIR__ . '/../../extensions/SemanticResultFormats',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'monolog/monolog' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'reference' => '1cb1cde8e8dd0f70cc0fe51354a59acad9302084',
            'type' => 'library',
            'install_path' => __DIR__ . '/../monolog/monolog',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'nicmart/tree' => array(
            'pretty_version' => 'v0.2.7',
            'version' => '0.2.7.0',
            'reference' => '0616b54bb49938e1a816141d7943db48ebf76938',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nicmart/tree',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'onoi/blob-store' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => 'c3e1f15214977e904fc0e91e0480175a464977ce',
            'type' => 'library',
            'install_path' => __DIR__ . '/../onoi/blob-store',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'onoi/cache' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'reference' => 'ecc999186aab7c8db411aedd892b2e5fe5a0b422',
            'type' => 'library',
            'install_path' => __DIR__ . '/../onoi/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'onoi/callback-container' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => 'cf2f4dda1b2479bc786985fdb5554af528d03e52',
            'type' => 'library',
            'install_path' => __DIR__ . '/../onoi/callback-container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'onoi/event-dispatcher' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '2af64e3997fc59b6d1e1f8f77e65fd6311c37109',
            'type' => 'library',
            'install_path' => __DIR__ . '/../onoi/event-dispatcher',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'onoi/message-reporter' => array(
            'pretty_version' => '1.4.2',
            'version' => '1.4.2.0',
            'reference' => 'ead8ef8f2868ccee6881e471295ebbaf8428c96c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../onoi/message-reporter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'oojs/oojs-ui' => array(
            'pretty_version' => 'v0.44.5',
            'version' => '0.44.5.0',
            'reference' => '49dffe151f28aa1556adca063d4faa82b2634822',
            'type' => 'library',
            'install_path' => __DIR__ . '/../oojs/oojs-ui',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'param-processor/param-processor' => array(
            'pretty_version' => '1.12.0',
            'version' => '1.12.0.0',
            'reference' => '0850dc2af72d31b8f645e0f87a44ff4b68583a64',
            'type' => 'library',
            'install_path' => __DIR__ . '/../param-processor/param-processor',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/console_getopt' => array(
            'pretty_version' => 'v1.4.3',
            'version' => '1.4.3.0',
            'reference' => 'a41f8d3e668987609178c7c4a9fe48fecac53fa0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/console_getopt',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/mail' => array(
            'pretty_version' => 'v1.5.1',
            'version' => '1.5.1.0',
            'reference' => '1665e1b1dc0261a15cb3ee99ef38b4254aa7564a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/mail',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/mail_mime' => array(
            'pretty_version' => '1.10.11',
            'version' => '1.10.11.0',
            'reference' => 'd4fb9ce61201593d0f8c6db629c45e29c3409c14',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/mail_mime',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/net_smtp' => array(
            'pretty_version' => '1.10.0',
            'version' => '1.10.0.0',
            'reference' => '51e5997b711fbd1e5a9a075634d4d682168537fa',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/net_smtp',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/net_socket' => array(
            'pretty_version' => 'v1.2.2',
            'version' => '1.2.2.0',
            'reference' => 'bbe6a12bb4f7059dba161f6ddd43f369c0ec8d09',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/net_socket',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/net_url2' => array(
            'pretty_version' => 'v2.2.2',
            'version' => '2.2.2.0',
            'reference' => '07fd055820dbf466ee3990abe96d0e40a8791f9d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/net_url2',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/pear-core-minimal' => array(
            'pretty_version' => 'v1.10.15',
            'version' => '1.10.15.0',
            'reference' => 'ce0adade8b97561656ace07cdaac4751c271ea8c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/pear-core-minimal',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/pear_exception' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'reference' => 'b14fbe2ddb0b9f94f5b24cf08783d599f776fff0',
            'type' => 'class',
            'install_path' => __DIR__ . '/../pear/pear_exception',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pleonasm/bloom-filter' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'reference' => '57c8cf69148fea2327dcf96b21ce50df7ede1dfc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pleonasm/bloom-filter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'reference' => '8622567409010282b7aeebe4bb841fe98b58dcaf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0.0',
            ),
        ),
        'psr/http-client' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'reference' => 'bb5906edc1c324c9a05aa0873d40117941e5fa90',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-client',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '2b4765fddfe3b508ac62f829e852b1501d3f6e8a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-factory-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'f6561bf28d520154e4b0ec72be95418abe6d9363',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0.0',
            ),
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'rsky/pear-core-min' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v1.10.15',
            ),
        ),
        'seld/jsonlint' => array(
            'pretty_version' => '1.8.3',
            'version' => '1.8.3.0',
            'reference' => '9ad6ce79c342fbd44df10ea95511a1b24dee5b57',
            'type' => 'library',
            'install_path' => __DIR__ . '/../seld/jsonlint',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'serialization/serialization' => array(
            'pretty_version' => '4.0.0',
            'version' => '4.0.0.0',
            'reference' => '6fa293415e2b70c30c1e673d8bcd04d27dc15e44',
            'type' => 'library',
            'install_path' => __DIR__ . '/../serialization/serialization',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/css-selector' => array(
            'pretty_version' => 'v5.4.40',
            'version' => '5.4.40.0',
            'reference' => 'ea43887e9afd2029509662d4f95e8b5ef6fc9bbb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/css-selector',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v2.5.3',
            'version' => '2.5.3.0',
            'reference' => '80d075412b557d41002320b96a096ca65aa2c98d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.99',
            ),
        ),
        'symfony/polyfill-mbstring' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.99',
            ),
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'v1.28.0',
            'version' => '1.28.0.0',
            'reference' => '6caa57379c4aec19c0a12a38b59b26487dcfe4b5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php81' => array(
            'pretty_version' => 'v1.28.0',
            'version' => '1.28.0.0',
            'reference' => '7581cd600fa9fd681b797d00b02f068e2f13263b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php81',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php82' => array(
            'pretty_version' => 'v1.28.0',
            'version' => '1.28.0.0',
            'reference' => '7716bea9c86776fb3362d6b52fe1fc9471056a49',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php82',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php83' => array(
            'pretty_version' => 'v1.28.0',
            'version' => '1.28.0.0',
            'reference' => 'b0f46ebbeeeda3e9d2faebdfbf4b4eae9b59fa11',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php83',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/yaml' => array(
            'pretty_version' => 'v5.4.23',
            'version' => '5.4.23.0',
            'reference' => '4cd2e3ea301aadd76a4172756296fe552fb45b0b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/assert' => array(
            'pretty_version' => 'v0.5.1',
            'version' => '0.5.1.0',
            'reference' => '27c983fddac1197dc37f6a7cec00fc02861529cd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/assert',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/at-ease' => array(
            'pretty_version' => 'v2.1.0',
            'version' => '2.1.0.0',
            'reference' => 'e8ebaa7bb7c8a8395481a05f6dc4deaceab11c33',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/at-ease',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/base-convert' => array(
            'pretty_version' => 'v2.0.2',
            'version' => '2.0.2.0',
            'reference' => 'aa997185e0b42c1f61a11f3e1980cad144175111',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/base-convert',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/cdb' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => '70c724f88faa74338c9918f5b999445a615593e8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/cdb',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/cldr-plural-rule-parser' => array(
            'pretty_version' => 'v2.0.0',
            'version' => '2.0.0.0',
            'reference' => '83d78cb8018d5c0f66fd6d0efff6a8ae2de92d36',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/cldr-plural-rule-parser',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/common-passwords' => array(
            'pretty_version' => 'v0.4.0',
            'version' => '0.4.0.0',
            'reference' => 'e16d64009724401d8ab870724322b88d11baa75c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/common-passwords',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/composer-merge-plugin' => array(
            'pretty_version' => 'v2.0.1',
            'version' => '2.0.1.0',
            'reference' => '8ca2ed8ab97c8ebce6b39d9943e9909bb4f18912',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../wikimedia/composer-merge-plugin',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/html-formatter' => array(
            'pretty_version' => '4.0.3',
            'version' => '4.0.3.0',
            'reference' => '9f3f30ad5d0287a1ca17c50bcbc45457db534208',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/html-formatter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/idle-dom' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'reference' => '631555d5868bf29427cb015906e666faf09abeea',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/idle-dom',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/ip-set' => array(
            'pretty_version' => '3.1.0',
            'version' => '3.1.0.0',
            'reference' => '9650ba486e21a84659fcfd46b3e5f2c4fa2b735c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/ip-set',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/ip-utils' => array(
            'pretty_version' => '4.0.0',
            'version' => '4.0.0.0',
            'reference' => 'f52a68b95fd3aac91cde3bdbc8654e2faa2fba38',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/ip-utils',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/less.php' => array(
            'pretty_version' => 'v4.4.1',
            'version' => '4.4.1.0',
            'reference' => '7d66ab6d38af72f80a0c0a3598d7feac04bbc7b7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/less.php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/minify' => array(
            'pretty_version' => '2.3.0',
            'version' => '2.3.0.0',
            'reference' => '61b35567bb3fb85c1086f30809cc67d5900c591f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/minify',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/normalized-exception' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'ed9fc13d75f65c80dc1a95d4792658c97fd782e6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/normalized-exception',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/object-factory' => array(
            'pretty_version' => 'v4.0.0',
            'version' => '4.0.0.0',
            'reference' => '20d19657cfbedb1e7bd61c6696e8a16ade232e5c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/object-factory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/parsoid' => array(
            'pretty_version' => 'v0.16.4',
            'version' => '0.16.4.0',
            'reference' => '31553436c0c0fa99518c2de524c0adb3c256a6fb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/parsoid',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/php-session-serializer' => array(
            'pretty_version' => 'v2.0.1',
            'version' => '2.0.1.0',
            'reference' => '40c9761329415ada958688d43ba4b8a447aa3037',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/php-session-serializer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/purtle' => array(
            'pretty_version' => 'v1.0.8',
            'version' => '1.0.8.0',
            'reference' => '8f106f38ff811906853511a934d7f5e86dce3d20',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/purtle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/relpath' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => 'b237d203c820cd1000f2c5ecad25de9fa7165612',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/relpath',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/remex-html' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '0997340924fb60a15590fc5001b6091c24fef1a3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/remex-html',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/request-timeout' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'reference' => 'e306a7cb1fb3a1ca3ce93992c56efb62b537c4bc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/request-timeout',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/running-stat' => array(
            'pretty_version' => 'v2.1.0',
            'version' => '2.1.0.0',
            'reference' => '0aa66cf58f98ca2de9972a8177cbec625c4c9969',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/running-stat',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/scoped-callback' => array(
            'pretty_version' => 'v4.0.0',
            'version' => '4.0.0.0',
            'reference' => 'dd522a6cfb4c0180b0a39d12fc57046a347c4d81',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/scoped-callback',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/services' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => 'c63d949c363378a5f435cfd7a81932aa6f712462',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/services',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/shellbox' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => '6b5abcd4a467b27b5ba4fc28f7730ea5d01367a1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/shellbox',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/textcat' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => 'dfdfb1c41bb016814a9d4da3aa68b62437b54a82',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/textcat',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/timestamp' => array(
            'pretty_version' => 'v4.1.1',
            'version' => '4.1.1.0',
            'reference' => '138f3099b46e3f6679ac100e5ab1932e89746a05',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/timestamp',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/utfnormal' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'reference' => 'e690d29487a6ee346bcf4cbf5a6fd89170fa2306',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/utfnormal',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/wait-condition-loop' => array(
            'pretty_version' => 'v2.0.2',
            'version' => '2.0.2.0',
            'reference' => '9bb0894e8c5195d43b2f2babbe4cc8f36bd5be0e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/wait-condition-loop',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/wikipeg' => array(
            'pretty_version' => '2.0.6',
            'version' => '2.0.6.0',
            'reference' => '9a92384ae11e1a3b7ecfe0feef1809b1af73889b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/wikipeg',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/wrappedstring' => array(
            'pretty_version' => 'v4.0.1',
            'version' => '4.0.1.0',
            'reference' => '0d526868d92fa855c70a845336a777c63b30b400',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/wrappedstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/xmp-reader' => array(
            'pretty_version' => '0.8.6',
            'version' => '0.8.6.0',
            'reference' => 'f2bc581314de73858d33c80c705da9b5644a996a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/xmp-reader',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/zest-css' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => '423c867462801fda08a1c31009ec19d91a68b410',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/zest-css',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'zordius/lightncandy' => array(
            'pretty_version' => 'v1.2.6',
            'version' => '1.2.6.0',
            'reference' => 'b451f73e8b5c73e62e365997ba3c993a0376b72a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../zordius/lightncandy',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
